import os
from dotenv import load_dotenv
load_dotenv()
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
GEMINI_MODEL = os.getenv('GEMINI_MODEL', 'gemini-3.5-flash-lite')
GEMINI_EMBEDDING_MODEL = os.getenv('GEMINI_EMBEDDING_MODEL', 'models/text-embedding-004')
GEMINI_MAX_RETRIES = int(os.getenv('GEMINI_MAX_RETRIES', '3'))
GEMINI_RETRY_DELAY = float(os.getenv('GEMINI_RETRY_DELAY', '1.5'))
GOOGLE_SEARCH_API_KEY = os.getenv('GOOGLE_SEARCH_API_KEY', '')
GOOGLE_CSE_ID = os.getenv('GOOGLE_CSE_ID', '')
EMBEDDING_MODEL = os.getenv('EMBEDDING_MODEL', 'all-MiniLM-L6-v2')
CHROMA_PATH = os.getenv('CHROMA_PATH', os.path.join(os.path.dirname(__file__), '..', 'data', 'chroma'))
CHROMA_COLLECTION = os.getenv('CHROMA_COLLECTION', 'course_docs')
CHUNK_SIZE_WORDS = int(os.getenv('CHUNK_SIZE_WORDS', '300'))
CHUNK_OVERLAP_WORDS = int(os.getenv('CHUNK_OVERLAP_WORDS', '50'))
DEFAULT_TOP_K = int(os.getenv('DEFAULT_TOP_K', '4'))
MIN_RELEVANCE_SCORE = float(os.getenv('MIN_RELEVANCE_SCORE', '0.30'))
ADMIN_PASSWORD = os.getenv('ADMIN_PASSWORD', 'changeme123')
UPLOAD_DIR = os.getenv('UPLOAD_DIR', os.path.join(os.path.dirname(__file__), '..', 'data', 'uploads'))
os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs(CHROMA_PATH, exist_ok=True)